### PR TITLE
Update optipng

### PR DESCRIPTION
**Pull request by Lofesa**
Update optipng to catch the latest commit in this library PR [#1](https://github.com/apache/incubator-pagespeed-optipng/commit/1fa893528ab66e208fa8b34b6e2518016bc6b1fb)

### CODE REVIEW

**Comment by oschaaf** [comment]
@Lofesa the system test `inline_unauthorized_resources allows inlining` seems to consistently fail with this, any idea why that is?

[1] https://github.com/apache/incubator-pagespeed-mod/blob/b4bf44cc56d8bbf17494c540dfb6ef20dfcf5073/pagespeed/system/system_tests/inline_unauth.sh#L26

**Comment by oschaaf** [comment]
(triggered CI on master, to see if this specific failure happens there too)

**Comment by Lofesa** [comment]
@oschaaf  No, I don´t know why the test fail, seems unrelated, the only change in this PR is update optipng library to the last commit on it. I don´t know if this PR is OK cause not only changes the folder, it add the changed file in the optipng library and includes the changes from the PR #1923. But I leave the PR as a reminder of this task and don´t close it.

EDIT: The test fail with a timeout. The latest updates to the Data-srcset PR fails in timeout, but not in the same test each time.

**Comment by oschaaf** [comment]
The latest on master fails on the same test, so it's probably an external dependency which has changed. I'll have a look at that

**Comment by oschaaf** [comment]
There are no more commits in this PR that aren't already merged to master. Closing!

**Pull request closed without merging**
