### PR TITLE
adding re2 bazel build

### PR DESCRIPTION
**Pull request by sambhajis-gdb**

### CODE REVIEW

**Comment by oschaaf** [comment]
Thanks!

So looking at https://github.com/google/re2/blob/e2deff36afd0a71adbf71cb11fba71ed2a407e4f/BUILD it seems this dependency could be added as a bazel native dependency.. Trying that, it seems that that no longer builds with recent bazel versions.

So what I do wonder about is: should we investigate upgrading re2 on the master branch?
If that works, we can probably go bazel native here by depending on a more recent version, instead of rolling our own `BUILD` file and injecting that.

So, let me attempt to upgrade `re2` on master, and follow up here to let you know how that went. If that turns out to be non-trivial, this is good as-is in my opinion, but if it's easy to upgrade `re2` it may make sense to go bazel-native here.

**Comment by oschaaf** [comment]
I think we can upgrade `re2`: https://github.com/apache/incubator-pagespeed-mod/pull/1915
ptal!

**Comment by oschaaf** [comment]
One note: I think `re2//:benchmark` replaces `re2//:bench_util` in the new `re2` version.
`mod_pagespeed_speed_test` relies on that. I think we should file an issue on this, and move on, we'll get to this once we get around to getting `mod_pagespeed_speed_test` to build, which will probably be a little further down the road.

**Comment by oschaaf** [comment]
PR for backporting the re2 upgrade to the `bazel` branch: https://github.com/apache/incubator-pagespeed-mod/pull/1916

**Review by oschaaf — APPROVED** [review]
Lgtm, thanks!

**Comment by sambhajis-gdb** [comment]
issue file for benchmark target #1917

**Pull request merged**
