### PR TITLE
Disable CSS (really font CSS in practice) inlining on AMP.

### PR DESCRIPTION
**Pull request by morlovich**
Ref: https://github.com/pagespeed/ngx_pagespeed/issues/1382

### CODE REVIEW

**Comment by oschaaf** [comment]
fwiw, looks good to me

**Comment by morlovich** [comment]
Well, that failure sure looks relevant, trying to see if I can reproduce it locally...

**Comment by oschaaf** [comment]
@morlovich ... It sure does, yes.

But did you note the other failure from `continuous-integration/travis-ci/push`? 
```
(98)Address already in use: make_sock: could not bind to address 127.0.0.1:8087
```
I wonder if something odd happened with these test runs..
Do you know if there is a way to respin these tests from the start (aside from pushing a change)?

**Comment by morlovich** [comment]
I think there may be a way in the Travis UI, but I don't feel comfortable giving it the permissions it wants...

**Comment by morlovich** [comment]
Well, it passed devel/checkin, FWIW...

**Comment by morlovich** [comment]
Hmm, saw the same failure as a flake on a totally different CL. I think I'll re-read the test...

**Comment by morlovich** [comment]
Huh, they're different a bit. In this one we seem to have had the font CSS inlined in fetch_util but not in the next line over wget_dump. The other one seem to have run into an experiment which tweaked the output some. I think I'll change the tests to at least use the same output for consistency, and change the comparison op to >= rather than =

**Comment by morlovich** [comment]
OK, maybe this will be a bit less flakey, PTAL.

**Review by jmarantz — APPROVED** [review]

**Pull request merged**
