### PR TITLE
Update gitmodules

### PR DESCRIPTION
**Pull request by Lofesa**
Update .gitmodules to change git.apache.org by github.com/apache

### CODE REVIEW

**Review by oschaaf — APPROVED** [review]
LGTM, great!

**Comment by mmilitzer** [comment]
I cannot update the Apache submodules anymore and I wonder if it's related to this pull request:

`git submodule update --init third_party/httpd/src
Submodule 'third_party/httpd/src' (https://github.com/apache/httpd.git) registered for path 'third_party/httpd/src'
Cloning into 'third_party/httpd/src'...
remote: Enumerating objects: 487867, done.
remote: Total 487867 (delta 0), reused 0 (delta 0), pack-reused 487867
Receiving objects: 100% (487867/487867), 301.73 MiB | 8.57 MiB/s, done.
Resolving deltas: 100% (406467/406467), done.
fatal: reference is not a tree: 493b43719686d9667831da5d5e063fb8fcd8c604
Unable to checkout '493b43719686d9667831da5d5e063fb8fcd8c604' in submodule path 'third_party/httpd/src'`

And it seems that this commit id that the submodule links to indeed does not exist in the apache httpd github repo...

**Comment by oschaaf** [comment]
Hmm, the last CI build log for master, which is this commit, didn't fail like that:
https://api.travis-ci.org/v3/job/591506645/log.txt

You can observe that it successfully pulled that commit. I just restarted the CI job to see if it reproduces there at this time. (https://travis-ci.org/apache/incubator-pagespeed-mod/builds/591506644)

**Comment by mmilitzer** [comment]
Are the submodules still cached somehow in your Travis build?

So also when I freshly clone the apache httpd repo and search for the commit id, it seems it's not there:

`git clone https://github.com/apache/httpd.git`
`git branch --contains 493b43719686d9667831da5d5e063fb8fcd8c604`
`error: no such commit 493b43719686d9667831da5d5e063fb8fcd8c604`

**Comment by Lofesa** [comment]
This PR only changes .gitmodules urls. nothing else.
The error you have say is not a tree
f`atal: reference is not a tree: 493b43719686d9667831da5d5e063fb8fcd8c604 Unable to checkout` 
but it is, as you can see [here](https://github.com/apache/httpd/tree/493b43719686d9667831da5d5e063fb8fcd8c604)

**Comment by hont512** [comment]
> error: no such commit 493b43719686d9667831da5d5e063fb8fcd8c604

I have it too.

With "git.apache.org" command "git submodule update --init --recursive" was OK
With "github.com/apache/" emmits this error

If I add **--remote** in addition, this error disappear, but another one come
`fatal: Needed a single revision`

**Comment by hont512** [comment]
It was fixed with:
`git add third_party/httpd`
`git add third_party/httpd24`
`git submodule update --init --recursive --force`

**Pull request merged**
