### PR TITLE
change some flaky system-tests to use fetch_all, to help them pass valgrind

### PR DESCRIPTION
**Pull request by jmarantz**

### CODE REVIEW

**Review by oschaaf — APPROVED** [review]
So to summarize: when we use `fetch_until`, we should combine it `fgrep` and add the `-save` flag, is that correct?

LGTM

**Comment by oschaaf** [comment]
(The Travis job timed out -- I just restarted it)

**Comment by jmarantz** [comment]
Actually now that I think of it, the -save flag is not necessary in either of these new cases.  I will remove them.  The -save flag is needed if, after the fetch_until, you want to do more analysis on the output.

**Review by ashishk-1 — APPROVED** [review]
LGTM

**Comment by oschaaf** [comment]
@jmarantz is this ready to go in?

**Pull request merged**
