### PR TITLE
fix for https://github.com/pagespeed/mod_pagespeed/issues/1623

### PR DESCRIPTION
**Pull request by deadjdona**
https://github.com/pagespeed/mod_pagespeed/issues/1623

### CODE REVIEW

**Review by oschaaf — APPROVED** [review]
Nice, LGTM!

**Comment by deadjdona** [comment]
I signed it!

**Comment by deadjdona** [comment]
I signed it!

**Comment by developexaccount** [comment]
I signed it!

**Review by jmarantz — APPROVED** [review]
thanks for the pull request!

**Pull request merged**
