### PR TITLE
add landing page for modpagespeed.com root

### PR DESCRIPTION
**Pull request by jeffkaufman**
Here's a port of https://developers.google.com/speed/pagespeed/module/ to modpagespeed.com.  This page is intended to go at the root, but I currently have it staged for review at https://modpagespeed.com/jefftk-index/

### CODE REVIEW

**Comment by jmarantz** [comment]
High level comments from looking at your page in staging:

1. You have most of the useful items in the current home-page header, except for a pointer to the source code (or maybe just the github projects).  Can you add that?  WDYT about pointing to ats_pagespeed and iispeed as well?

2. Formatting-wise, I am disturbed by how little horizontal space is used on my wide monitor.  There's an excessive amount of vertical whitespace too.  Can you tweak this a little?  I think it should be easy to see everything at a glance without scrolling on a modest laptop.  One thing you could do is make these sections be inline-blocks so that on a mobile screen you can scroll vertically to see all of them.

**Comment by jeffkaufman** [comment]
> a pointer to the source code (or maybe just the github projects). Can you add that?

Added

> WDYT about pointing to ats_pagespeed and iispeed as well?

Added

> One thing you could do is make these sections be inline-blocks so that on a mobile screen you can scroll vertically to see all of them.

Done (though it ended up being harder than that, because css is a pain)

All in 12dcfcd6b

**Comment by jeffkaufman** [comment]
@oschaaf Do you have any thoughts on this?  I'm not attached to the design at all (and not especially design-capable)

**Comment by oschaaf** [comment]
@jeffkaufman the mobile version looks perfect to me, but let me see if I can tweak the desktop version a bit. On a larger screen, the horizontal and vertical whitespace gets a bit excessive. Let me see if I can help out, I'll prepare a pull to your branch.

**Comment by oschaaf** [comment]
Done - one question though, where will the examples go?

**Comment by jmarantz** [comment]
Good catch -- there should be a link in the home page to
"/mod_pagespeed_examples/index.html"

**Comment by jeffkaufman** [comment]
We're fine for CLA status: the commit it's complaining about is from @oschaaf , who created the commit specifically to be merged here.

**Comment by jmarantz** [comment]
Jeff can you update https://modpagespeed.com/jefftk-index/ with the latest merged version?

**Comment by jeffkaufman** [comment]
> Jeff can you update https://modpagespeed.com/jefftk-index/ with the latest merged version?

Done!

```
jeff@local ~ $ ssh modpagespeed.com
modpagespeed@modpagespeed.com:~$ cd modpagespeed-jefftk-testing
modpagespeed@modpagespeed-com:~/modpagespeed-jefftk-testing$ git pull
```

**Review by jmarantz — APPROVED** [review]

**Comment by jeffkaufman** [comment]
Notes for whoever deploys this change:

Right now modpagespeed.com is configured with `mod_pagespeed_examples.tar.gz` unpacked to `/var/www/html/mod_pagespeed_example` and the files there symlinked to root.  We need to remove those symlinks and add redirects, except for the root index.html which should be the file in this change.

Possibly we should stop with a separate `mod_pagespeed_examples.tar.gz` all together, and just use the `mod_pagespeed_example` directory in git.

(See https://github.com/pagespeed/mod_pagespeed/wiki/Updating-modpagespeed.com-and-ngxpagespeed.com)

**Pull request closed without merging**
