### PR TITLE
WIP: Update grpc to v1.17.2 to make grpc OpenSSL 1.1 compatible

### PR DESCRIPTION
**Pull request by nberlee**
DO NOT MERGE YET
In order to have OpenSSL compatibility we need to update grpc to a > 1.16.0 version. (also need to update third_party/serf/instaweb_ssl_buckets.c bio_ functions but I will create a separate issue for that)

Still needs work pagespeed/controller/grpc_server_test.o but I am not a C programmer:
```
pagespeed/controller/expensive_operation_rpc_context_test.cc:124:39: error: cannot declare field 'net_instaweb::{anonymous}::ExpensiveOperationRpcContextTest::stub_' to be of abstract type 'net_instaweb::MockCentralControllerRpcServiceStub'
   MockCentralControllerRpcServiceStub stub_;
                                       ^~~~~
In file included from pagespeed/controller/expensive_operation_rpc_context_test.cc:21:0:
./pagespeed/controller/controller_grpc_mocks.h:165:7: note:   because the following virtual functions are pure within 'net_instaweb::MockCentralControllerRpcServiceStub':
 class MockCentralControllerRpcServiceStub
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./pagespeed/controller/controller_grpc_mocks.h:20:0,
                 from pagespeed/controller/expensive_operation_rpc_context_test.cc:21:
out/Release/obj/gen/protoc_out/instaweb/pagespeed/controller/controller.grpc.pb.h:107:137: note: 	virtual grpc::ClientAsyncReaderWriterInterface<net_instaweb::ScheduleRewriteRequest, net_instaweb::ScheduleRewriteResponse>* net_instaweb::grpc::CentralControllerRpcService::StubInterface::PrepareAsyncScheduleRewriteRaw(grpc::ClientContext*, grpc::CompletionQueue*)
     virtual ::grpc::ClientAsyncReaderWriterInterface< ::net_instaweb::ScheduleRewriteRequest, ::net_instaweb::ScheduleRewriteResponse>* PrepareAsyncScheduleRewriteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
                                                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
out/Release/obj/gen/protoc_out/instaweb/pagespeed/controller/controller.grpc.pb.h:110:159: note: 	virtual grpc::ClientAsyncReaderWriterInterface<net_instaweb::ScheduleExpensiveOperationRequest, net_instaweb::ScheduleExpensiveOperationResponse>* net_instaweb::grpc::CentralControllerRpcService::StubInterface::PrepareAsyncScheduleExpensiveOperationRaw(grpc::ClientContext*, grpc::CompletionQueue*)
     virtual ::grpc::ClientAsyncReaderWriterInterface< ::net_instaweb::ScheduleExpensiveOperationRequest, ::net_instaweb::ScheduleExpensiveOperationResponse>* PrepareAsyncScheduleExpensiveOperationRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
                                                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pagespeed/controller/expensive_operation_rpc_context_test.cc: In member function 'virtual void net_instaweb::{anonymous}::ExpensiveOperationRpcContextTest_SuccessfulRequest_Test::TestBody()':
pagespeed/controller/expensive_operation_rpc_context_test.cc:132:56: error: invalid new-expression of abstract class type 'net_instaweb::MockReaderWriterT<net_instaweb::ScheduleExpensiveOperationRequest, net_instaweb::ScheduleExpensiveOperationResponse>'
   MockReaderWriter* rw = new MockReaderWriter(sequence_);
                                                        ^
In file included from pagespeed/controller/expensive_operation_rpc_context_test.cc:21:0:
./pagespeed/controller/controller_grpc_mocks.h:70:7: note:   because the following virtual functions are pure within 'net_instaweb::MockReaderWriterT<net_instaweb::ScheduleExpensiveOperationRequest, net_instaweb::ScheduleExpensiveOperationResponse>':
 class MockReaderWriterT
       ^~~~~~~~~~~~~~~~~
In file included from third_party/grpc/src/include/grpcpp/impl/codegen/async_generic_service.h:22:0,
                 from out/Release/obj/gen/protoc_out/instaweb/pagespeed/controller/controller.grpc.pb.h:27,
                 from ./pagespeed/controller/controller_grpc_mocks.h:20,
                 from pagespeed/controller/expensive_operation_rpc_context_test.cc:21:
third_party/grpc/src/include/grpcpp/impl/codegen/async_stream.h:42:16: note: 	virtual void grpc::internal::ClientAsyncStreamingInterface::StartCall(void*)
   virtual void StartCall(void* tag) = 0;
                ^~~~~~~~~
pagespeed/controller/expensive_operation_rpc_context_test.cc: In member function 'virtual void net_instaweb::{anonymous}::ExpensiveOperationRpcContextTest_SuccessfulRequestWithPointerSteal_Test::TestBody()':
pagespeed/controller/expensive_operation_rpc_context_test.cc:162:56: error: invalid new-expression of abstract class type 'net_instaweb::MockReaderWriterT<net_instaweb::ScheduleExpensiveOperationRequest, net_instaweb::ScheduleExpensiveOperationResponse>'
   MockReaderWriter* rw = new MockReaderWriter(sequence_);
                                                        ^
pagespeed/controller/expensive_operation_rpc_context_test.cc: In member function 'virtual void net_instaweb::{anonymous}::ExpensiveOperationRpcContextTest_UnsuccessfulRequest_Test::TestBody()':
pagespeed/controller/expensive_operation_rpc_context_test.cc:197:56: error: invalid new-expression of abstract class type 'net_instaweb::MockReaderWriterT<net_instaweb::ScheduleExpensiveOperationRequest, net_instaweb::ScheduleExpensiveOperationResponse>'
   MockReaderWriter* rw = new MockReaderWriter(sequence_);
                                                        ^
pagespeed/controller/expensive_operation_rpc_context_test.cc: In member function 'virtual void net_instaweb::{anonymous}::ExpensiveOperationRpcContextTest_InitFailed_Test::TestBody()':
pagespeed/controller/expensive_operation_rpc_context_test.cc:225:56: error: invalid new-expression of abstract class type 'net_instaweb::MockReaderWriterT<net_instaweb::ScheduleExpensiveOperationRequest, net_instaweb::ScheduleExpensiveOperationResponse>'
   MockReaderWriter* rw = new MockReaderWriter(sequence_);
                                                        ^
pagespeed/controller/expensive_operation_rpc_context_test.cc: In member function 'virtual void net_instaweb::{anonymous}::ExpensiveOperationRpcContextTest_FinishFailed_Test::TestBody()':
pagespeed/controller/expensive_operation_rpc_context_test.cc:255:56: error: invalid new-expression of abstract class type 'net_instaweb::MockReaderWriterT<net_instaweb::ScheduleExpensiveOperationRequest, net_instaweb::ScheduleExpensiveOperationResponse>'
   MockReaderWriter* rw = new MockReaderWriter(sequence_);
                                                        ^
pagespeed/controller/expensive_operation_rpc_context_test.cc: In member function 'virtual void net_instaweb::{anonymous}::ExpensiveOperationRpcContextTest_FirstWriteFailed_Test::TestBody()':
pagespeed/controller/expensive_operation_rpc_context_test.cc:284:56: error: invalid new-expression of abstract class type 'net_instaweb::MockReaderWriterT<net_instaweb::ScheduleExpensiveOperationRequest, net_instaweb::ScheduleExpensiveOperationResponse>'
   MockReaderWriter* rw = new MockReaderWriter(sequence_);
                                                        ^
pagespeed/controller/expensive_operation_rpc_context_test.cc: In member function 'virtual void net_instaweb::{anonymous}::ExpensiveOperationRpcContextTest_ReadFailed_Test::TestBody()':
pagespeed/controller/expensive_operation_rpc_context_test.cc:313:56: error: invalid new-expression of abstract class type 'net_instaweb::MockReaderWriterT<net_instaweb::ScheduleExpensiveOperationRequest, net_instaweb::ScheduleExpensiveOperationResponse>'
   MockReaderWriter* rw = new MockReaderWriter(sequence_);
                                                        ^
pagespeed/controller/expensive_operation_rpc_context_test.cc: In member function 'virtual void net_instaweb::{anonymous}::ExpensiveOperationRpcContextTest_SecondWriteFailed_Test::TestBody()':
pagespeed/controller/expensive_operation_rpc_context_test.cc:345:56: error: invalid new-expression of abstract class type 'net_instaweb::MockReaderWriterT<net_instaweb::ScheduleExpensiveOperationRequest, net_instaweb::ScheduleExpensiveOperationResponse>'
   MockReaderWriter* rw = new MockReaderWriter(sequence_);
                                                        ^
make[1]: *** [net/instaweb/pagespeed_automatic_test.target.mk:680: out/Release/obj.target/pagespeed_automatic_test/pagespeed/controller/expensive_operation_rpc_context_test.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:209: build_libraries] Error 2
```

### CODE REVIEW

**Comment by oschaaf** [comment]
@nberlee let me know if you need any help with this

**Comment by nmichaud2** [comment]
Any update on this ?

**Comment by oschaaf** [comment]
Upgraded to `1.6.8` in https://github.com/apache/incubator-pagespeed-mod/pull/1890; 
That can be done without having to maintain the build system.
Still ,we ought to upgrade to a later version.

**Comment by oschaaf** [comment]
@ashishk-1 this is worth taking a look at with respect to upgrading GRPC. I am not sure if this is outdated / if/how grpc has diverged since this PR was opened, but gyp file changes have already been made here, which may perhaps save you some time

**Comment by csandanov** [comment]
Any updates?

**Comment by oschaaf** [comment]
Closing this: on master we now piggy back on Envoy for the grpc & openssl deps.

**Pull request closed without merging**
