### PR TITLE
A few tweaks to jefftk-landing's proposed index.html

### PR DESCRIPTION
**Pull request by oschaaf**
- Make the logo render much better in MS Edge
- Change logo positioning
- Reduce vertical whitespace
- Attempt to get a clearer overview of topics by adding
  dashed lines between them

Preview at http://mps.we-amp.com/

### CODE REVIEW

**Comment by jeffkaufman** [comment]
The logo positioning looks broken to me:

image

And:

image

**Comment by jeffkaufman** [comment]
Everything else looks good to me.

**Comment by oschaaf** [comment]
@jeffkaufman banner re-positioned!

**Comment by jeffkaufman** [comment]
LGTM

**Pull request merged**
