### PR TITLE
update libwebp to 1.0.1

### PR DESCRIPTION
**Pull request by nberlee**

### CODE REVIEW

**Review by jmarantz — COMMENTED** [review]
The changes look fine, although I'm wondering why the golded sizes of images increased. Any thoughts or insights into why this might be?

**Comment by nberlee** [comment]
I think I tracked it down to:
https://chromium.googlesource.com/webm/libwebp/+/815652de03377339aee55f048dd41f581853f0ef

see filesizes of webp in issues and and some mentions of the filesize in issue 308 comment 3, issue 340 comment 7
https://bugs.chromium.org/p/webp/issues/detail?id=308#c3 
https://bugs.chromium.org/p/webp/issues/detail?id=340#c7

**Comment by oschaaf** [comment]
Nice, looking over the webp changelist, I think this would be a good to incorporate. 
The CI failure looks like it isn't a flake though, we need to take care of more file size changes..

**Comment by oschaaf** [comment]
Closing this: we now rely on bazel to manage deps, and libwebp has been upgraded to the latest on master.

**Pull request closed without merging**
